In [1]:
import numpy as np

A = np.array([[1], [2], [3]])
A_1d = A.flatten()
C = np.array([[1, 4, 2], [2, 7, 3], [3, 5, 8], [2, 1, 0]])

print("A:\n", A, "\nA_1d:\n", A_1d, "\nA.T:\n", A.T)
print("C:\n", C,"\nC.T:\n", C.T)
print("\n")
print("■ np.dot(A_1d,A_1d):",np.dot(A_1d,A_1d),"\n dot product is usually used with 1D (rank1) arrays\n\
  It will behave as matmul if used with 2d arrays\n")

print("■ A*C | np.matmul(A,C) | np.dot(A,C) | np.multiply(A,C):\n\
  All Don't work cuz (3,1)x(4,3)\n")

print("■ C*A | np.multiply(C, A): Doesn't work (4,3)x(3,1)")
print("■ np.matmul(C,A):\n(4,3)x(3,1)=(4,1) good old matrix multiplication\nWhat's needed to get the Z vector when C is weights and A is X (features of one example)\n", np.matmul(C,A))
print("■ np.dot(C, A):\nSame result as matmul in this case\n", np.dot(C, A), "\n")

print("■ A.T *C (np.multiply(A.T, C)):\n(1,3)x(4,3):A.T gets broadcasted and element-wise multiplication takes place)\n", A.T * C)
print("■ np.matmul(A.T, C) | np.dot(A.T,C):\nDoesn't work cuz (1,3)x(4,3)\n")

print("■ C*A.T (np.multiply(C, A.T)):\n(4,3)x(1,3): Same as A.T * C\nA.T gets broadcasted and element-wise multiplication takes place)\n", C*A.T)
print("■ np.matmul(C, A.T) | np.dot(C, A.T):\nDoesn't work cuz (4,3)x(1,3)\n")

print("■ C.T*A (np.multiply(C.T, A)):\n(3,4)x(3,1): A gets broadcasted and element-wise multiplication takes place)\n", C.T*A)
print("■ np.matmul(C.T, A) | np.dot(C, A.T):\nDoesn't work cuz (3,4)x(3,1)\n")

print("■ A*C.T (np.multiply(A, C.T)):\n(3,1)x(3,4)\n", np.multiply(A, C.T))
print("■ np.matmul(A, C.T) | np.dot(A, C.T):\nDoesn't work cuz (3,1)x(3,4)\n")

print("A*A.T\n", A*A.T)
print("np.matmul(A, A.T)\n", np.matmul(A, A.T))
print("np.dot(A,A.T)\n", np.dot(A,A.T))

print("A*A\n", A*A)



A:
 [[1]
 [2]
 [3]] 
A_1d:
 [1 2 3] 
A.T:
 [[1 2 3]]
C:
 [[1 4 2]
 [2 7 3]
 [3 5 8]
 [2 1 0]] 
C.T:
 [[1 2 3 2]
 [4 7 5 1]
 [2 3 8 0]]


■ np.dot(A_1d,A_1d): 14 
 dot product is usually used with 1D (rank1) arrays
  It will behave as matmul if used with 2d arrays

■ A*C | np.matmul(A,C) | np.dot(A,C) | np.multiply(A,C):
  All Don't work cuz (3,1)x(4,3)

■ C*A | np.multiply(C, A): Doesn't work (4,3)x(3,1)
■ np.matmul(C,A):
(4,3)x(3,1)=(4,1) good old matrix multiplication
What's needed to get the Z vector when C is weights and A is X (features of one example)
 [[15]
 [25]
 [37]
 [ 4]]
■ np.dot(C, A):
Same result as matmul in this case
 [[15]
 [25]
 [37]
 [ 4]] 

■ A.T *C (np.multiply(A.T, C)):
(1,3)x(4,3):A.T gets broadcasted and element-wise multiplication takes place)
 [[ 1  8  6]
 [ 2 14  9]
 [ 3 10 24]
 [ 2  2  0]]
■ np.matmul(A.T, C) | np.dot(A.T,C):
Doesn't work cuz (1,3)x(4,3)

■ C*A.T (np.multiply(C, A.T)):
(4,3)x(1,3): Same as A.T * C
A.T gets broadcasted and element-wise multip